// v342 (בקשת המשתמש 05/10/2026): דפדוף בגלילת דף כמו בקינדל — גאומטריה טהורה + החיבור לקורא
const fs = require('fs');
const path = require('path');
let n = 0;
function ok(c, name) { n++; if (!c) { console.error('FAIL - ' + name); process.exit(1); } console.log('ok - ' + name); }
const root = path.join(__dirname, '..');
const src = fs.readFileSync(path.join(root, 'pagecurl.js'), 'utf8');
const lib = fs.readFileSync(path.join(root, 'library.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'library.css'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const { swVersionOk } = require('./_swver.js');
const M = {};
const names = [...src.matchAll(/^export function (\w+)/gm)].map((m) => m[1]);
new Function('M', src.replace(/^export /gm, '') + '\n' + names.map((k) => 'M.' + k + ' = ' + k + ';').join('\n'))(M);
const W = 400, H = 800, near = (a, b) => Math.abs(a - b) < 1e-6;
const area = (P) => Math.abs(P.reduce((a, q, i) => { const w = P[(i + 1) % P.length]; return a + q[0] * w[1] - w[0] * q[1]; }, 0)) / 2;
const ap = (m, X) => [m[0] * X[0] + m[2] * X[1] + m[4], m[1] * X[0] + m[3] * X[1] + m[5]];
ok(!/^import /m.test(src) && !/document\.|window\./.test(src.split('export function createCurl')[0]), 'בלי ייבוא ובלי DOM בטעינה (נבדק ב־node)');
let g = M.curlGeom(W, H, 0, 0, 400, false);
ok(near(area(g.front), W * H) && near(area(g.turned), 0), 'p=0: הדף שטוח');
const r = M.curlRadius(W);
g = M.curlGeom(W, H, 0.25, 0, 400, false);
const fx = g.front.map((p) => p[0]);
ok(near(Math.max(...fx), 300) && near(Math.min(...fx), 0), 'p=0.25: ציר הגליל ב־x=300, החלק השטוח בצד השדרה');
const rx = g.roll.map((p) => p[0]);
ok(near(Math.min(...rx), 300) && near(Math.max(...rx), 300 + r), 'הגליל: רצועה ברוחב r מעבר לציר');
const e = ap(g.m, [400, 123]);
ok(near(e[0], 300 - (100 - Math.PI * r)) && near(e[1], 123), 'גב הדף: הקצה החופשי נוחת ב־ציר − (d − πr) — מה שעל הגליל לא נפרש');
const rr = ap(g.m, ap(g.m, [37, 91]));
ok(near(rr[0], 37) && near(rr[1], 91), 'שיקוף פעמיים = זהות');
const gr = M.curlGeom(W, H, 0.25, 0, 400, true);
ok(near(Math.min(...gr.front.map((p) => p[0])), 100) && near(Math.max(...gr.front.map((p) => p[0])), 400), 'ספר RTL: הקצה החופשי משמאל, השדרה מימין');
const ge = M.curlGeom(W, H, M.curlEnd(W, H, 0), 0, 400, false);
ok(near(area(ge.front), 0) && near(area(ge.roll), 0), 'סוף הדפדוף: הדף והגליל מחוץ למסך');
const gt = M.curlGeom(W, H, 0.4, M.curlTilt(0.4, 720, 0, H), 720, false);
const top = gt.front.filter((p) => p[1] === 0).map((p) => p[0]), bot = gt.front.filter((p) => p[1] === H).map((p) => p[0]);
ok(Math.max(...bot) < Math.max(...top) - 40 && Math.abs(M.curlTilt(0.4, 400, 0, H)) < 0.08, 'הטיה כמו בקינדל — אחיזה בתחתית: הפינה התחתונה מובילה');
ok(M.curlTilt(0, 700, 0, H) === 0 && Math.abs(M.curlTilt(1, 700, 0, H)) < 1e-9, 'הטיה 0 בתחילת ובסוף הדפדוף');
ok(M.curlProgress(1, 0, W, H) === 0 && near(M.curlProgress(-1, 0, W, H), M.curlEnd(W, H, 0)) && M.curlProgress(1, 200, W, H) > 0.25, 'התקדמות לפי האצבע (אחורה — מתחיל כשהדף הקודם מחוץ למסך)');
ok(M.curlCommit(1, 0.05, 0.002) && !M.curlCommit(1, 0.05, 0) && M.curlCommit(1, 0.3, 0) && !M.curlCommit(1, 0.3, -0.002) && M.curlCommit(1, 0.03, 0.0002), 'קדימה: האצבע זזה לכיוון — מדפדף (גם החלקה קצרה שמאטה); עצירה — לפי המרחק; חזרה — מבטל');
ok(M.curlCommit(-1, 1.0, -0.002, 1.08) && !M.curlCommit(-1, 1.07, 0, 1.08) && M.curlCommit(-1, 0.6, 0, 1.08), 'אחורה: אותו כלל בכיוון ההפוך');
ok(/linear-gradient\(/.test(M.gradAt(W, H, [200, 400], [1, 0], [[0, 'red'], [10, 'blue']])), 'מעבר צבע לאורך הציר');
// החיבור לקורא
ok(/import\('\.\/pagecurl\.js'\)/.test(lib) && /if \(reduceMotion\(\)\) return;/.test(lib.split('async function curlSetup')[1].slice(0, 80)), 'נטען בעצלתיים; תנועה מופחתת — ההחלקה הרגילה');
ok(/curlTouch\(e, r\.left, r\.top, holdOff\);\s*\}, \{ capture: true, passive: false \}\)/.test(lib), 'במסמך הספר: לפני המנוע (capture)');
ok(/view\.addEventListener\(ty, \(e\) => curlTouch\(e, 0, 0, null\), \{ capture: true, passive: false \}\)/.test(lib), 'גם בשולי העמוד');
ok(/e\.stopPropagation\(\); if \(e\.cancelable\) e\.preventDefault\(\);/.test(lib), 'הגרירה של המנוע לא מקבלת את התנועה');
ok(/r\.removeAttribute\('animated'\)/.test(lib) && /q = q\.then\(\(\) => env\.jump\(dir\)\)/.test(src), 'מעבר עמוד מיידי במנוע, בתור (המנוע נעול 100ms אחרי כל מעבר)');
// v343: המנוע לא זז בזמן המחווה (החלפת מסמך הפרק באמצע נגיעה בלעה את האצבע)
const beginSrc = src.split('function begin(')[1].split('\n  function move(')[0];
ok(!/jump\(/.test(beginSrc) && /if \(go\) \{[\s\S]{0,600}?turnedLayers[\s\S]{0,320}?await jump\(s\.dir\);/.test(src), 'המעבר האמיתי — רק בסוף דפדוף שהושלם; ביטול — בלי מעבר');
ok(/ensureNeighbor\('next'\); ensureNeighbor\('prev'\);/.test(src) && /env\.loadSection\(i\)/.test(src) && /st\.textContent = env\.bookCss\(\)/.test(src), 'פרק שכן נטען מראש, באותו עיצוב — גב הדף עם טקסט גם בין פרקים');
ok(/ct\.plain = dir/.test(lib) && /\(d > 0 \? r\.next\(\) : r\.prev\(\)\)/.test(lib), 'הפרק השכן עוד לא מוכן — מעבר רגיל (ההחלקה לא נבלעת)');
ok(/curlGeom\(W, H, g\.p, g\.phi, g\.gy, g\.rtl, curlRadius\(W\), g\.T\)/.test(src) && /u_kc/.test(src), 'הסגנון שהמשתמש אהב: גליל צר קבוע + כנף מוגבלת; חרוט עדין לאורך הציר (כמו בקינדל)');
ok(/u_ls\.xy \+ \(pos\.xy - u_ls\.xy\) \* \(u_ls\.z/.test(src) && /LIGHT = Array\.from\(\{ length: 32 \}/.test(src) && /gl\.stencilOp\(gl\.KEEP, gl\.KEEP, gl\.INCR\)/.test(src), 'צל רך פיזיקלי: מקור אור שטחי, 32 דגימות, כל פיקסל נספר פעם אחת לדגימה');
ok(/curlMotion\(dist, rushSpeed\(SPEED/.test(src) && /SPEED = 1\.12/.test(src), 'מהירות קבועה ובלימה בקצה כמו בקינדל (נמדד 1.37 רוחבי מסך/שנ׳; אצלנו 1.12 — קצת לאט, בקשת המשתמש, v345; v346 — פיזיקה רציפה מהשחרור)');
ok(/if \(c\.active\(\)\) c\.finishNow\(\);/.test(lib), 'דפדוף מהיר ברצף — הקודם מסתיים מיד');
ok(/curlPrebuild\(\)/.test(lib.split("view.addEventListener('relocate'")[1].slice(0, 2500)) && /curlStyleVer\+\+/.test(lib), 'שכפול הפרק נבנה מראש אחרי מעבר עמוד ושינוי עיצוב');
ok(/if \(r\.curl\) r\.curl\.destroy\(\)/.test(lib), 'ניקוי בסגירת הקורא');
ok(/setAttribute\('sandbox', 'allow-same-origin'\)/.test(src), 'השכפול בלי סקריפטים');
ok(/\.rd foliate-view \{ z-index: 2; \}/.test(css) && /\.rd-ribbon \{[^}]*z-index: 6;/.test(css) && /\.rd-topbar, \.rd-botbar \{ z-index: 7; \}/.test(css), 'שכבות: הסימנייה והסרגלים מעל הדפדוף');
const v = (app.match(/APP_VERSION = '(v\d+)'/) || [])[1];
ok(!!v && swVersionOk(v), 'גרסה');
console.log(`\n${n} בדיקות עברו`);
